feat(aws)!: Add Support for Cost Explorer data
cloudquery/cloudquery pull request #10288
Opened 2023-04-24 20:19 UTC by bbernays

#### Summary

BEGIN_COMMIT_OVERRIDE
feat(aws)!: Add Support for Cost Explorer data
BREAKING-CHANGE: Cost Explorer data incurs a cost for every request, so to avoid being charged make sure to not include the `aws_costexplorer*` tables in your sync
END_COMMIT_OVERRIDE

2023-04-25 07:07 UTC, candiduslynx requested changes

2023-04-25 07:07 UTC, candiduslynx commented on plugins/source/aws/client/spec.go
> +	SkipNonFreeAPIs           bool      `json:"use_non_free_apis"`
```suggestion
	UseNonFreeAPIs            bool      `json:"use_non_free_apis"`
```

2023-04-25 07:07 UTC, candiduslynx commented on plugins/source/aws/resources/services/costexplorer/cost_current_month.go
> +	if !cl.Spec.SkipNonFreeAPIs {
```suggestion
	if !cl.Spec.UseNonFreeAPIs {
```

2023-04-25 07:07 UTC, candiduslynx commented on plugins/source/aws/resources/services/costexplorer/cost_current_month_mock_test.go
> +	client.AwsMockTestHelper(t, CurrentMonthCost(), buildCurrentMonthCost, client.TestOptions{})
also need to enable paid calls for test client

2023-04-25 07:07 UTC, candiduslynx commented on plugins/source/aws/resources/services/costexplorer/forecast_current_month.go
> +	if !cl.Spec.SkipNonFreeAPIs {
```suggestion
	if !cl.Spec.UseNonFreeAPIs {
```

2023-04-25 08:33 UTC, disq commented on plugins/source/aws/client/spec.go
> +	SkipNonFreeAPIs           bool      `json:"use_non_free_apis"`
```suggestion
	IncludePaidAPIs           bool      `json:"include_paid_apis"`
```
I think this is today's consensus :)

2023-04-25 17:01 UTC, disq requested changes

2023-04-25 17:01 UTC, disq commented on website/tables/aws/awscost_costexplorer_cost_current_month.md
> +This table shows data for Awscost Costexplorer Cost Current Month.
To fix this you should edit resources/plugin/plugin.go and add it to `awsExceptions`

2023-04-25 22:42 UTC, bbernays commented on plugins/source/aws/resources/services/costexplorer/cost_current_month.go
> +	tableName := "awscost_costexplorer_cost_current_month"
This was a remnant from when I had this in a standalone plugin

2023-04-26 07:24 UTC, candiduslynx requested changes

2023-04-26 07:24 UTC, candiduslynx commented on plugins/source/aws/docs/tables/README.md
> +- [awscost_costexplorer_forecast_current_month](../../../../../website/tables/aws/awscost_costexplorer_forecast_current_month.md)
why it's not after `aws_costexplorer_cost_current_month`?

2023-04-26 07:24 UTC, candiduslynx commented on plugins/source/aws/resources/services/costexplorer/forecast_current_month.go
> +	tableName := "awscost_costexplorer_forecast_current_month"
```suggestion
	tableName := "aws_costexplorer_forecast_current_month"
```

2023-04-26 07:24 UTC, candiduslynx commented on plugins/source/aws/resources/services/costexplorer/cost_current_month.go
> +		cl.Logger().Info().Msg("skipping `awscost_costexplorer_cost_current_month` because `include_paid_apis` is set to false")
```suggestion
		cl.Logger().Info().Msg("skipping `aws_costexplorer_cost_current_month` because `include_paid_apis` is set to false")
```

2023-04-26 07:24 UTC, candiduslynx commented on plugins/source/aws/resources/services/costexplorer/forecast_current_month.go
> +		cl.Logger().Info().Msg("skipping `awscost_costexplorer_forecast_current_month` because `include_paid_apis` is set to false")
```suggestion
		cl.Logger().Info().Msg("skipping `aws_costexplorer_forecast_current_month` because `include_paid_apis` is set to false")
```

2023-04-26 07:24 UTC, candiduslynx commented on website/pages/docs/plugins/sources/aws/configuration.md
> +  When set to `true` plugin will sync data from APIs that incur a fee. Currently only `aws_costexplorer*` tables requires this flag to be set to true.
```suggestion
  When set to `true` plugin will sync data from APIs that incur a fee. Currently only `aws_costexplorer*` tables require this flag to be set to `true`.
```

2023-04-26 10:45 UTC, disq requested changes
Looks like only things left are some awscost remnants and typos as reviewed by 
@candiduslynx and adding to `awsExceptions` in `resources/plugin/plugin.go` to make the table docs better.

2023-04-26 14:51 UTC, candiduslynx approved these changes
Still requires cost explorer to bedded to custom description transformation map in plugin init.

2023-04-26 18:02 UTC, candiduslynx approved these changes

2023-04-26 18:50 UTC, disq approved these changes

2023-04-26 18:50 UTC, merged