feat(file): Use new writer
cloudquery/cloudquery pull request #10649
Opened 2023-05-09 13:13 UTC by disq

Example on how to utilize https://github.com/cloudquery/plugin-sdk/pull/855

I don't like the `lastSpec` part, but I don't want to change the method signature. But maybe a small change can be OK, as opposed to doing things like embedding it into ctx and so on.

2023-06-16 11:54 UTC, candiduslynx requested changes
I suggest moving to https://pkg.go.dev/sync#Map

2023-06-16 11:54 UTC, candiduslynx commented on plugins/destination/file/go.mod
> +replace github.com/cloudquery/filetypes/v3 => github.com/cloudquery/filetypes/v3 v3.1.1-0.20230525203919-7a1d60739423
IMO this can already be removed

2023-06-16 11:54 UTC, candiduslynx commented on plugins/destination/file/go.mod
> +replace github.com/cloudquery/plugin-sdk/v3 => github.com/disq/plugin-sdk/v3 v3.0.0-20230525203908-a2e923d19b8e
is the required PR merged?

2023-06-16 11:54 UTC, candiduslynx commented on plugins/destination/file/client/write.go
> +	c.tableFiles[key] = writer{
```suggestion
	c.tableFiles[mapKey(sourceSpec, table)] = writer{
```

2023-06-16 11:54 UTC, candiduslynx commented on plugins/destination/file/client/write.go
> +}
```suggestion
	key := mapKey(sourceSpec, table)
	tFile := c.tableFiles[key]
	delete(c.tableFiles, key)

	err := tFile.h.WriteFooter()
	err2 := tFile.f.Close()
	if err != nil {
		return err
	}
	return err2
}
```

2023-06-16 11:54 UTC, candiduslynx commented on plugins/destination/file/client/write.go
> +	c.tableFilesMu.Lock()
can sync.Map be used instead (we can use https://pkg.go.dev/sync#Map.LoadAndDelete for this one)?

2023-06-19 19:44 UTC, disq commented
Closing for sdk v4

2023-06-19 19:44 UTC, closed without merging