feat(aws): add private certificate authorities
cloudquery/cloudquery pull request #10691
Opened 2023-05-10 03:35 UTC by adam-tylr

#### Summary

Adds support for acmpca certificate authorities. 

Tests for this resource are currently failing with the below output. Not sure if there's something simple I'm missing with that table not synched line. Any pointers?

```
--- FAIL: TestACMPCACertificateAuthorities (0.04s)
    certificate_authorities_mock_test.go:47: Expected table aws_acmpca_certificate_authorities to be synced but it was not found
    controller.go:137: missing call(s) to *mocks.MockAcmpcaClient.ListCertificateAuthorities(is anything, is equal to &{<nil> <nil>  {}} (*acmpca.ListCertificateAuthoritiesInput), is anything) /Users/adamtyler/workspace/cloudquery/plugins/source/aws/resources/services/acmpca/certificate_authorities_mock_test.go:22
    controller.go:137: missing call(s) to *mocks.MockAcmpcaClient.ListTags(is anything, is equal to &{0xc00060e7a0 <nil> <nil> {}} (*acmpca.ListTagsInput), is anything) /Users/adamtyler/workspace/cloudquery/plugins/source/aws/resources/services/acmpca/certificate_authorities_mock_test.go:31
    controller.go:137: aborting test due to missing call(s)
FAIL
FAIL    github.com/cloudquery/cloudquery/plugins/source/aws/resources/services/acmpca   0.331s
```

2023-05-10 13:37 UTC, bbernays requested changes
Overall this looks great! A few minor tweaks to get the tests passing!

2023-05-10 13:37 UTC, bbernays commented on plugins/source/aws/resources/services/acmpca/certificate_authorities.go
> +		Multiplex:   client.ServiceAccountRegionMultiplexer(tableName, "acmpca"),
The name of the service in this location has to match the name that AWS [uses here](https://github.com/cloudquery/cloudquery/blob/66eefda579565b4e76647daf36ca21070d338f59/plugins/source/aws/client/data/partition_service_region.json#L79)

so in this case the service name is `acm-pca`

2023-05-10 13:37 UTC, bbernays commented on plugins/source/aws/resources/services/acmpca/certificate_authorities.go
> +	certAuthority := resource.Item.(*types.CertificateAuthority)
```suggestion
	certAuthority := resource.Item.(types.CertificateAuthority)
```

2023-05-10 13:37 UTC, bbernays commented on plugins/source/aws/resources/services/acmpca/certificate_authorities.go
> +	paginator := acmpca.NewListCertificateAuthoritiesPaginator(svc, &input)
```suggestion
	paginator := acmpca.NewListCertificateAuthoritiesPaginator(svc, nil)
```

2023-05-10 21:33 UTC, adam-tylr commented
Thanks @bbernays, `make test` is passing now

2023-05-11 13:03 UTC, bbernays commented
@adam-tylr Can you run `go mod tidy`?

2023-05-11 21:21 UTC, bbernays approved these changes
LGTM! Once the tests all pass this should merge

2023-05-13 18:45 UTC, adam-tylr commented
@bbernays Any idea about the failed check?

2023-05-15 14:32 UTC, bbernays commented
@adam-tylr - That test is now passing 😄 ... But unfortunately there are conflicts in the go mod now 😭 ...

2023-05-16 11:21 UTC, hermanschaaf approved these changes

2023-05-16 11:22 UTC, hermanschaaf commented
Thanks for this contribution @adam-tylr, looks great!

2023-05-16 11:37 UTC, merged