chore(datadog): Move fetch functions, add back codegen for services
cloudquery/cloudquery pull request #10816
Opened 2023-05-16 13:50 UTC by hermanschaaf

This change:
 - restores the services codegen code accidentally removed in https://github.com/cloudquery/cloudquery/pull/6424. We are still relying on it for the generation of service interfaces and mocks
 - moves resolvers out of `_fetch.go` files into the main resource files, as is now standard practice
 - updates the contribution guide

There are no user-facing changes here, only refactoring and developer-facing changes.

2023-05-16 13:56 UTC, hermanschaaf commented on plugins/source/datadog/codegen/services/generate.go
> +package services
This file was just restored from the Git history, no changes

2023-05-16 17:43 UTC, candiduslynx requested changes
needs to point to plugin-sdk/v2, others are nits

2023-05-16 17:43 UTC, candiduslynx commented on plugins/source/datadog/CONTRIBUTING.md
> + 1. open `codegen/services/clients.go` and add the client from the Datadog SDK to the list of clients
```suggestion
 1. Open `codegen/services/clients.go` and add the client from the Datadog SDK to the list of clients
```

2023-05-16 17:43 UTC, candiduslynx commented on plugins/source/datadog/CONTRIBUTING.md
> + 2. run `make gen-mocks` to generate the service interface and mocks
```suggestion
 2. Run `make gen-mocks` to generate the service interface and mocks
```

2023-05-16 17:43 UTC, candiduslynx commented on plugins/source/datadog/go.mod
> +	github.com/cloudquery/plugin-sdk v1.24.0
I really think this shouldn't be here anymore

2023-05-16 17:43 UTC, candiduslynx commented on plugins/source/datadog/codegen/services/generate.go
> +	"github.com/cloudquery/plugin-sdk/caser"
```suggestion
	"github.com/cloudquery/plugin-sdk/v2/caser"
```

2023-05-17 15:19 UTC, hermanschaaf commented on plugins/source/datadog/CONTRIBUTING.md
> + 2. run `make gen-mocks` to generate the service interface and mocks
Updated, thanks for the suggestion

2023-05-17 15:49 UTC, candiduslynx approved these changes

2023-05-17 15:50 UTC, merged