feat(okta)!: Make token param required & drop `OKTA_API_TOKEN` env variable support
cloudquery/cloudquery pull request #10887
Opened 2023-05-22 14:14 UTC by candiduslynx

2023-05-22 14:16 UTC, bbernays requested changes
Why would we want to break backwards compatibility for this?

2023-05-22 14:18 UTC, candiduslynx commented
> Why would we want to break backwards compatibility for this?

@bbernays 

It's a cleanup as we did in Git(Lab?Hub?) and Tailscale.

Additionally, I'd like to merge this along with the v3 migration, as that one would already be a breaking change.

2023-05-22 14:21 UTC, bbernays commented
> > Why would we want to break backwards compatibility for this?
> 
> @bbernays
> 
> It's a cleanup as we did in Git(Lab?Hub?) and Tailscale.
> 
> Additionally, I'd like to merge this along with the v3 migration, as that one would already be a breaking change.

What is the improved experience or functionality that users will get by us forcing them to adjust their configurations?


But the V3 migration shouldn't require users to adjust their configurations other than the destination version...

2023-05-22 14:32 UTC, candiduslynx commented
> What is the improved experience or functionality that users will get by us forcing them to adjust their configurations?

We streamline the code base here (no direct env lookups in plugins). It's more of the dev experience change.



> But the V3 migration shouldn't require users to adjust their configurations other than the destination version...

It will still be a breaking change per the types changes and the need to use updated destinations as well.
So, it feels like a good moment to add an additional breaking change.

2023-05-22 15:28 UTC, hermanschaaf submitted a review, later dismissed
I agree, let's not do a breaking change only for the sake of removing a few lines / consistency with other plugins.

Instead, maybe we can start by logging a warning if you use `OKTA_API_TOKEN` without setting `token` in the config, and say this is marked for deprecation and will be removed in a future version?

2023-05-23 11:14 UTC, candiduslynx commented
@hermanschaaf @bbernays 
I've changed the PR to only print out a warning about this variable + added the warning to the config example & overview.

2023-05-23 12:46 UTC, bbernays commented on plugins/source/okta/client/spec.go
> +		logger.Warn().Msgf("usage of %q environment variable value is deprecated and will be dropped in the future releases", OktaAPIToken)
```suggestion
		logger.Warn().Msgf("usage of %q environment variable value is deprecated and will be dropped in a future release", OktaAPIToken)
```

2023-05-23 15:15 UTC, bbernays approved these changes

2023-05-24 07:06 UTC, merged