feat(datadog)!: Upgrade to SDK V3 Arrow native
cloudquery/cloudquery pull request #10976
Opened 2023-05-25 16:53 UTC by yevgenypats

BEGIN_COMMIT_OVERRIDE
feat: Update to use [Apache Arrow](https://arrow.apache.org/) type system

BREAKING-CHANGE: This release introduces an internal change to our type system to use [Apache Arrow](https://arrow.apache.org/). This should not have any visible breaking changes, however due to the size of the change we are introducing it under a major version bump to communicate that it might have some bugs that we weren't able to catch during our internal tests. If you encounter an issue during the upgrade, please submit a [bug report](https://github.com/cloudquery/cloudquery/issues/new/choose).

You will also need to update destinations depending on which one you use:
Azure Blob Storage >= v3.2.0
BigQuery >= v3.0.0
ClickHouse >= v3.1.1
DuckDB >= v1.1.6
Elasticsearch >= v2.0.0
File >= v3.2.0
Firehose >= v2.0.2
GCS >= v3.2.0
Gremlin >= v2.1.10
Kafka >= v3.0.1
Meilisearch >= v2.0.1
Microsoft SQL Server >= v4.2.0
MongoDB >= v2.0.1
MySQL >= v2.0.2
Neo4j >= v3.0.0
PostgreSQL >= v4.2.0
S3 >= v4.4.0
Snowflake >= v2.1.1
SQLite >= v2.2.0

END_COMMIT_OVERRIDE

2023-05-25 16:56 UTC, yevgenypats commented
Closes https://github.com/cloudquery/cloudquery/issues/10738

2023-05-26 07:36 UTC, candiduslynx requested changes

2023-05-26 07:36 UTC, candiduslynx commented on plugins/source/datadog/go.mod
>  	github.com/cloudquery/plugin-sdk/v2 v2.7.0
this shouldn't be there (only as indirect). You need to search where you left v2 reference

2023-05-26 07:36 UTC, candiduslynx commented on plugins/source/datadog/resources/services/monitors/monitor_downtimes.go
> +				Type:     arrow.BinaryTypes.String,
gen header should be removed?

2023-05-26 07:36 UTC, candiduslynx commented on plugins/source/datadog/resources/services/roles/role_permissions.go
> +	"github.com/cloudquery/plugin-sdk/v2/types"
```suggestion
	"github.com/cloudquery/plugin-sdk/v3/types"
```

2023-05-26 12:45 UTC, candiduslynx approved these changes

2023-05-26 12:53 UTC, merged