feat(digitalocean)!: Migrate to Arrow native SDK
cloudquery/cloudquery pull request #10980
Opened 2023-05-25 17:37 UTC by disq

Closes #10739

BEGIN_COMMIT_OVERRIDE
feat: Update to use [Apache Arrow](https://arrow.apache.org/) type system

BREAKING-CHANGE: This release introduces an internal change to our type system to use [Apache Arrow](https://arrow.apache.org/). This should not have any visible breaking changes, however due to the size of the change we are introducing it under a major version bump to communicate that it might have some bugs that we weren't able to catch during our internal tests. If you encounter an issue during the upgrade, please submit a [bug report](https://github.com/cloudquery/cloudquery/issues/new/choose).

You will also need to update destinations depending on which one you use:
Azure Blob Storage >= v3.2.0
BigQuery >= v3.0.0
ClickHouse >= v3.1.1
DuckDB >= v1.1.6
Elasticsearch >= v2.0.0
File >= v3.2.0
Firehose >= v2.0.2
GCS >= v3.2.0
Gremlin >= v2.1.10
Kafka >= v3.0.1
Meilisearch >= v2.0.1
MSSQL >= v4.2.0
MongoDB >= v2.0.1
MySQL >= v2.0.2
Neo4j >= v3.0.0
PostgreSQL >= v4.2.0
S3 >= v4.4.0
Snowflake >= v2.1.1
SQLite >= v2.2.0

END_COMMIT_OVERRIDE

2023-05-25 17:38 UTC, yevgenypats approved these changes

2023-05-25 17:39 UTC, yevgenypats commented
Actually not sure why it says there are breaking changes. I think it shouldn't maybe something up with the diff tooling

2023-05-26 07:12 UTC, candiduslynx requested changes

2023-05-26 07:12 UTC, candiduslynx commented on plugins/source/digitalocean/go.mod
> +	github.com/cloudquery/plugin-sdk/v3 v3.6.2
```suggestion
	github.com/cloudquery/plugin-sdk/v3 v3.6.4
```

2023-05-26 08:41 UTC, candiduslynx commented
@disq I've rebased to see if the table diff will be regenerated

2023-05-26 08:46 UTC, candiduslynx requested changes

2023-05-26 08:46 UTC, candiduslynx commented on .github/workflows/release_summary.yml
> +      - "website/pages/docs/plugins/sources/*/tables/*"
```suggestion
```

2023-05-26 08:46 UTC, candiduslynx commented on plugins/source/digitalocean/resources/services/monitoring/alert_policies.go
> +				Resolver:   schema.PathResolver("UUID"),
shouldn't it be UUID?

2023-05-26 08:50 UTC, candiduslynx approved these changes

2023-05-26 11:08 UTC, merged