feat: Send connection issues to analytics
cloudquery/cloudquery pull request #1102
Opened 2022-07-05 08:31 UTC by irmatov

Closes https://github.com/cloudquery/cloudquery-issues/issues/370

2022-07-11 06:35 UTC, roneli requested changes
Nice idea for adding more meta analytic information, we do need to update the docs after this PR merges. Added some thoughts here.

2022-07-11 06:35 UTC, roneli commented on cmd/fetch/fetch.go
> +}
I can see this growing into many event types, we currently have fetch and policy, but in this case we can have more.
Maybe call this event type "diag" and give it sub types and some meta information as occurrence count etc' and by no means to pass the "error" itself as that can have user information we don't want.

ill let @bbernays  weigh in some more here.

2022-07-23 21:12 UTC, yevgenypats requested changes
Let's hold on with that as it uses Diags which are going away in the upcoming weeks - https://github.com/cloudquery/cq-provider-sdk/pull/437

2022-08-11 19:34 UTC, yevgenypats commented
Closing as we move to cloudquery v2 and error reporting is different

2022-08-11 19:34 UTC, closed without merging