feat(gcp): Folder searching
cloudquery/cloudquery pull request #11202
Opened 2023-06-02 22:45 UTC by bbernays

#### Summary

Enables users to use a query string to search for folders rather than recursively finding all folders and then ignoring specific projects

closes: #11165

2023-06-02 22:46 UTC, bbernays commented on plugins/source/gcp/client/spec.go
> +	FolderFilter          string   `json:"folder_filter"`
Need to add docs for this

2023-06-02 22:47 UTC, bbernays commented on plugins/source/gcp/client/spec.go
>  	FolderRecursionDepth  *int     `json:"folder_recursion_depth"`
In the future I think we should deprecate this. No need to use the recursion if we can just use a simple search query

2023-06-05 07:33 UTC, erezrokah approved these changes

2023-06-05 18:26 UTC, bbernays commented
This PR doesn't actually solve the issue. This only enables users to use a different discovery method

2023-06-19 10:21 UTC, erezrokah reviewed
Thanks for the PR @bbernays, does having a single filter for each type of resource won't cover all uses cases?

For example if we have only a `projects_filter` users can:
```
include ids -> id:project-1 AND id:project-2
exclude ids -> NOT id:project-3
include + exclude names -> name:* AND NOT name:test*
```

2023-06-19 12:46 UTC, bbernays commented
> Thanks for the PR @bbernays, does having a single filter for each type of resource will cover all uses cases?
> 
> For example if we have only a `projects_filter` users can:
> 
> ```
> include ids -> id:project-1 AND id:project-2
> exclude ids -> NOT id:project-3
> include + exclude names -> name:* AND NOT name:test*
> ```

There is nothing that stops users from doing that as it is in this implementation, but I thought that it would get very messy for users to have a single super long query rather than a list of queries... The goal of this was to keep the functionality it as explicit as possible

2023-06-19 13:02 UTC, erezrokah commented
> There is nothing that stops users from doing that as it is in this implementation, but I thought that it would get very messy for users to have a single super long query rather than a list of queries... The goal of this was to keep the functionality it as explicit as possible

I'm not sure we should have multiple ways to do the same thing in this case. Maybe we could start only with the filter and add the more explicit methods later if needed? I'm worried that:
1. We're building an abstraction over GCP filter expressions
2. It's harder to communicate how our custom logic works instead of pointing to GCP docs and say we're passing through the expression directly so the logics matches `gcloud * list --filter`

We can add some examples in our docs on how to include/exclude project IDs, etc.

2023-06-19 13:17 UTC, bbernays commented
I have removed the `exclude_filter` option, but left the `include_filter` to be explicit that the results will be included

2023-06-19 15:50 UTC, erezrokah commented
> We already know that users use the hard-coded lists now why would we want to take away that user experience?

We are also adding exclude list which is more logic that implements on our end what the filter does on the backend.
I don't mind keeping the existing include list, but it does mean we'll be doing more API requests than needed to get the same data (I would even translate that list to a filter based query instead of iterating over the ids).

2023-06-19 16:03 UTC, erezrokah reviewed
Added a few comments but could we also maybe trim the API requests to a single filter?
For example:

1. User configures only filter -> use that directly
2. User configures only include list of IDs -> transform to an `OR` filter on all IDs
3. User configures both -> create a new filter that does an `OR` between the configured one an the ID based `OR` filter from `2.`

Am I missing a use case with the above approach?

2023-06-19 16:54 UTC, bbernays commented on plugins/source/gcp/client/spec.go
> +	IncludeFilter []string `json:"include_filter"`
Keeping it as an array of strings gives users more flexibility without a significant impact on usability... If we started with a string we would have to break backwards compatibility to add support...

2023-06-19 16:57 UTC, bbernays commented
> > We already know that users use the hard-coded lists now why would we want to take away that user experience?
> 
> We are also adding exclude list which is more logic that implements on our end what the filter does on the backend. I don't mind keeping the existing include list, but it does mean we'll be doing more API requests than needed to get the same data (I would even translate that list to a filter based query instead of iterating over the ids).



> Added a few comments but could we also maybe trim the API requests to a single filter? For example:
> 
> 1. User configures only filter -> use that directly
> 2. User configures only include list of IDs -> transform to an `OR` filter on all IDs
> 3. User configures both -> create a new filter that does an `OR` between the configured one an the ID based `OR` filter from `2.`
> 
> Am I missing a use case with the above approach?

I really like that idea and I think this is a super interesting + powerful approach! I sort of want to do it in a follow up PR once we are aligned on the user facing pieces though

2023-06-19 17:52 UTC, erezrokah commented on plugins/source/gcp/client/spec.go
> +	IncludeFilter []string `json:"include_filter"`
> Keeping it as an array of strings gives users more flexibility without a significant impact on usability... If we started with a string we would have to break backwards compatibility to add support...

What kind of flexibility are we getting? It seems we're implementing the `OR` functionality that already exists in the current filter syntax

2023-06-25 12:55 UTC, yevgenypats commented
What is the status on that one? did we decide we keep the complexity at bay at the end and not introduce more options?

2023-06-25 13:02 UTC, yevgenypats requested changes
How do we intend to test this?

2023-06-26 09:05 UTC, erezrokah commented
> What is the status on that one?

I'll spend some time today looking at the different built-in filtering logic GCP provides. Maybe we can assume some best practices on folders/projects/organizations structure to simplify filtering logic

2023-06-26 09:33 UTC, yevgenypats commented
> > What is the status on that one?
> 
> I'll spend some time today looking at the different built-in filtering logic GCP provides. Maybe we can assume some best practices on folders/projects/organizations structure to simplify filtering logic

I think for such a complex feature which ads more complexity (and going back that I think we should simplify the current config even more and remove the org option and not add more options) we should wait for more users to ask for it and not rush it especially as there is a work-around.

2023-09-22 06:35 UTC, erezrokah commented
Going to close this as stale, we still have the code as reference

2023-09-22 06:35 UTC, closed without merging