feat(datadog): Update to SDK v4
cloudquery/cloudquery pull request #11945
Opened 2023-07-04 14:09 UTC by yevgenypats

2023-07-04 14:10 UTC, yevgenypats commented
Closes https://github.com/cloudquery/cloudquery/issues/11946

2023-07-04 15:33 UTC, candiduslynx requested changes

2023-07-04 15:33 UTC, candiduslynx commented on website/tables/datadog/datadog_slos.md
> +This table shows data for Datadog Slos.
this needs to be put back

2023-07-04 15:33 UTC, candiduslynx commented on website/tables/datadog/datadog_slo_corrections.md
> +This table shows data for Datadog Slo Corrections.
```suggestion
This table shows data for Datadog SLO Corrections.
```

2023-07-04 15:33 UTC, candiduslynx commented on plugins/source/datadog/resources/plugin/tables.go
> +}
```suggestion
func titleTransformer() func (table *schema.Table) {
	if table.Title != "" {
		return table.Title
	}
	exceptions := make(map[string]string)
	maps.Copy(exceptions, docs.DefaultTitleExceptions)
	maps.Copy(exceptions, customExceptions)
	csr := caser.New(caser.WithCustomExceptions(exceptions))
	return func (table *schema.Table) {
		table.Title =  csr.ToTitle(table.Name)
	}
}
```
 [`maps.Copy`](https://pkg.go.dev/golang.org/x/exp/maps#Copy)

2023-07-04 15:33 UTC, candiduslynx commented on plugins/source/datadog/resources/plugin/plugin.go
> +	if err := c.scheduler.Sync(ctx, c.client.Duplicate(), tables, res, scheduler.WithSyncDeterministicCQID(options.DeterministicCQID)); err != nil {
just ret? (nit)
```suggestion
	return c.scheduler.Sync(ctx, c.client.Duplicate(), tables, res, scheduler.WithSyncDeterministicCQID(options.DeterministicCQID))
```

2023-07-04 15:33 UTC, candiduslynx commented on plugins/source/datadog/client/testing.go
> +	inserts := []*message.SyncInsert{}
```suggestion
	var inserts := message.SyncInserts
```

2023-07-04 15:33 UTC, candiduslynx commented on plugins/source/datadog/client/client.go
> +func (c *Client) Duplicate() schema.ClientMeta {
is it used?

2023-07-05 10:19 UTC, merged

2023-07-05 10:28 UTC, candiduslynx commented on plugins/source/datadog/resources/plugin/tables.go
> +		titleTransformer(table)
@yevgenypats 
using this will construct the csr for each table, instead of constructing caser once & reusing it for all transformations, though