feat: Add AWS SSM Parameters resource
cloudquery/cloudquery pull request #1222
Opened 2022-08-12 08:40 UTC by spangenberg

Fixes: https://github.com/cloudquery/cq-provider-aws/issues/1376

2022-08-15 18:50 UTC, yevgenypats requested changes
Looks good but some tests failing

2022-08-16 12:30 UTC, erezrokah commented on plugins/source/aws/resources/services/ssm/parameters_mock_test.go
> +	"github.com/cloudquery/cq-provider-aws/client/mocks"
```suggestion
	"github.com/cloudquery/cloudquery/plugins/source/aws/client"
	"github.com/cloudquery/cloudquery/plugins/source/aws/client/mocks"
```

2022-08-16 12:31 UTC, erezrokah commented on plugins/source/aws/resources/services/ssm/parameters.hcl
> +    path = "github.com/cloudquery/cq-provider-aws/client.IgnoreAccessDeniedServiceDisabled"
```suggestion
    path = "github.com/cloudquery/cloudquery/plugins/source/aws/client.IgnoreAccessDeniedServiceDisabled"
```

2022-08-16 12:53 UTC, erezrokah commented on plugins/source/aws/resources/services/ssm/parameters.hcl
> +      path = "github.com/cloudquery/cq-provider-aws/client.ResolveAWSRegion"
```suggestion
      path = "github.com/cloudquery/cloudquery/plugins/source/aws/client.ResolveAWSRegion"
```

2022-08-16 12:53 UTC, erezrokah commented on plugins/source/aws/resources/services/ssm/parameters.hcl
> +      path = "github.com/cloudquery/cq-provider-aws/client.ResolveAWSAccount"
```suggestion
      path = "github.com/cloudquery/cloudquery/plugins/source/aws/client.ResolveAWSAccount"
```

2022-08-16 12:53 UTC, erezrokah commented on plugins/source/aws/resources/services/ssm/parameters.hcl
> +    path   = "github.com/cloudquery/cq-provider-aws/client.ServiceAccountRegionMultiplexer"
```suggestion
    path   = "github.com/cloudquery/cloudquery/plugins/source/aws/client.ServiceAccountRegionMultiplexer"
```

2022-08-16 16:47 UTC, merged