feat(aws): Replace DelegationSetId with full DelegationSet in AWS Hos…
cloudquery/cloudquery pull request #12737
Opened 2023-08-02 22:41 UTC by kfritchman46

…tZone table

#### Summary

The default (not reusable) DelegationSet of AWS public HostedZones are only visible when describing the HostedZone. The DelegationSet API doesn't include them. Sync should include the DelegationSet as a json field of the `aws_route53_hosted_zones` table so changes in Nameservers can be detected.

2023-08-03 10:13 UTC, erezrokah requested changes
Thanks for the PR @kfritchman46, can we still keep `DelegationSetId`? That would make this change non breaking for existing users

2023-08-04 16:22 UTC, kfritchman46 commented
@erezrokah Absolutely, I wasn't sure how strict this project is on clutter vs reducing breaking changes. I'll update.

2023-08-07 09:13 UTC, erezrokah approved these changes

2023-08-07 09:15 UTC, erezrokah commented
> @erezrokah Absolutely, I wasn't sure how strict this project is on clutter vs reducing breaking changes. I'll update.

Thanks for following up, looks great 🚀 . We try to avoid breaking changes as it requires consumers of the data to drop existing tables in most cases

2023-08-07 09:38 UTC, merged