feat: support reading private key from string
cloudquery/cloudquery pull request #13556
Opened 2023-08-31 15:35 UTC by patriknordlen

#### Summary

This PR addresses #13555 by adding a `private_key` configuration key that can be used to read the private key from a string instead of a file.

2023-08-31 20:10 UTC, patriknordlen commented on plugins/source/github/client/client.go
> +		var k *rsa.PrivateKey
Thanks for pushing a fix! The PR is ready for review.

2023-09-01 09:11 UTC, erezrokah requested changes
Thanks for following up @patriknordlen, added a couple of comments regarding the error messages

2023-09-01 09:11 UTC, erezrokah commented on plugins/source/github/client/spec.go
> +			return fmt.Errorf("missing private key specification in configuration")
```suggestion
			return fmt.Errorf("missing private key specification in configuration. Please specify using either `private_key` or `private_key_path`")
```

2023-09-01 09:11 UTC, erezrokah commented on plugins/source/github/client/spec.go
> +			return fmt.Errorf("both private key and private key path specified in configuration")
```suggestion
			return fmt.Errorf("both private key and private key path specified in configuration. Please remove the configuration for either `private_key_path` or `private_key`")
```

2023-09-01 09:47 UTC, patriknordlen commented
> Thanks for following up @patriknordlen, added a couple of comments regarding the error messages

Thanks for the suggestions, accepted and committed!

2023-09-01 10:02 UTC, erezrokah approved these changes

2023-09-01 11:53 UTC, merged