Add status badges to readme
cloudquery/cloudquery pull request #14535
Opened 2023-10-15 16:21 UTC by R3DRUN3

#### Summary
*Safe to merge PR*  
added `license`, `go report`, `ci` and `latest release` status badges to readme to improve docs quality.  
Take a look at the edited readme in [my fork](https://github.com/R3DRUN3/cloudquery/blob/main/README.md).

2023-10-15 19:57 UTC, candiduslynx commented
Hi @R3DRUN3!
Thanks for the PR, it looks great!

Just one thing I'd like to change: we have a monorepo here, so the latest release will point sometimes to some plugins, sometimes to CLI. Is it possible to get the latest CLI release only? We tag them in a specific pattern, so it'll be easy to query.

2023-10-16 07:31 UTC, candiduslynx requested changes
Need to figure out a way to point only to the CLI release (or drop the release badge altogether)

2023-10-16 09:16 UTC, R3DRUN3 commented
> Need to figure out a way to point only to the CLI release (or drop the release badge altogether)

@candiduslynx unfortunately, it appears that there is no straightforward and efficient method for selectively referencing only the CLI releases.  
Consequently, I have removed the badge for the latest release.

2023-10-16 09:25 UTC, erezrokah approved these changes

2023-10-16 09:30 UTC, merged