feat: Add JSON schema to elasticsearch destination
cloudquery/cloudquery pull request #16489
Opened 2024-02-02 14:34 UTC by disq

Closes https://github.com/cloudquery/cloudquery/issues/16448

2024-02-02 14:35 UTC, disq commented on plugins/destination/elasticsearch/client/spec.go
>  		s.Addresses = []string{"http://localhost:9200"}
This is very basic and Validate() is empty... doesn't make a good json schema :)

2024-02-02 19:05 UTC, candiduslynx requested changes

2024-02-02 19:05 UTC, candiduslynx commented on plugins/destination/elasticsearch/client/schema.json
> +              "description": "A list of Elasticsearch nodes to use. (Default: [\"http://localhost:9200\"])"
you can actually use `default` here

2024-02-02 19:05 UTC, candiduslynx commented on plugins/destination/elasticsearch/client/schema.json
> +          "description": "Endpoint for the Elastic Service (https://elastic.co/cloud)."
wrong desc?

2024-02-02 19:05 UTC, candiduslynx commented on plugins/destination/elasticsearch/client/spec.go
> +	Addresses []string `json:"addresses"`
```suggestion
	Addresses []string `json:"addresses" jsonschema:"default=http://localhost:9200"`
```

2024-02-02 19:05 UTC, candiduslynx commented on plugins/destination/elasticsearch/client/spec.go
> +	// Endpoint for the Elastic Service (https://elastic.co/cloud).
is it a proper desc?

2024-02-02 20:39 UTC, disq commented on plugins/destination/elasticsearch/client/schema.json
> +          "description": "Endpoint for the Elastic Service (https://elastic.co/cloud)."
No it's correct.

2024-02-02 20:40 UTC, disq commented on plugins/destination/elasticsearch/client/spec.go
> +	// Endpoint for the Elastic Service (https://elastic.co/cloud).
That's what the doc says.

2024-02-03 08:11 UTC, candiduslynx approved these changes
only a small nit

2024-02-03 08:11 UTC, candiduslynx commented on plugins/destination/elasticsearch/client/spec.go
> +	// A list of Elasticsearch nodes to use. (Default: ["http://localhost:9200"])
No need for default repetition here.
```suggestion
	// A list of Elasticsearch nodes to use.
```

2024-02-03 08:14 UTC, candiduslynx approved these changes

2024-02-03 08:16 UTC, merged