feat: Add support for Private docker registries
cloudquery/cloudquery pull request #16837
Opened 2024-02-23 15:58 UTC by bbernays

#### Summary

Depends on https://github.com/cloudquery/plugin-pb-go/pull/248

2024-02-23 16:07 UTC, bbernays commented
> I think we need to run
> 
> https://github.com/cloudquery/cloudquery/blob/f957b492fc28e34096ccd585063ee546937fae74/cli/Makefile#L15
> 
> too

Agreed, but also need to get this merged and then released https://github.com/cloudquery/plugin-pb-go/pull/248

2024-02-26 14:00 UTC, erezrokah requested changes
Looks good, one comment on the docs

2024-02-26 14:00 UTC, erezrokah commented on website/pages/docs/reference/source-spec.md
> +echo -n "{\"username\":\"USERNAME\",\"password\":\"$$CR_PAT\"}" | base64
```suggestion
echo -n "{\"username\":\"USERNAME\",\"password\":\"$CR_PAT\"}" | base64
```

Is the double `$$` on purpose?

2024-02-26 14:12 UTC, erezrokah approved these changes

2024-02-26 14:51 UTC, merged