feat: Migrate Okta plugin to v2
cloudquery/cloudquery pull request #1781
Opened 2022-09-09 11:44 UTC by disq

2022-09-11 16:06 UTC, yevgenypats requested changes
Can you please open a new okta account and manually test it ?

2022-09-12 08:58 UTC, disq commented
> Can you please open a new okta account and manually test it ?

seems to work!

2022-09-13 21:15 UTC, yevgenypats requested changes
Looks good. one comment and ready to go.

2022-09-13 21:15 UTC, yevgenypats commented on plugins/source/okta/client/spec.go
> +	Token  string `yaml:"token,omitempty"`
it should be json (we use json everywhere apart from the first step in the CLI where we read yaml and then convert to json - just like in k8s)

2022-09-14 21:33 UTC, yevgenypats approved these changes

2022-09-14 22:13 UTC, merged