test(cli): Add integration tests for
cloudquery/cloudquery pull request #1848
Opened 2022-09-18 13:31 UTC by erezrokah

#### Summary

Adds basic integration tests. The `sync` test is failing due to a bug in our release pipeline (not embedding versions) which I'll fix in a separate PR

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Test locally on your own infrastructure
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation)) 
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

2022-09-18 13:32 UTC, erezrokah commented on .github/workflows/test_build.yml
> +  test-build:
Keep casing consistent

2022-09-18 13:32 UTC, erezrokah commented on .github/workflows/test_build.yml
> -  CQ_NO_TELEMETRY: 1
I don't think we need this anymore

2022-09-18 13:32 UTC, erezrokah commented on .github/workflows/test_integration.yml
> +  check-cli-changes:
This should save spinning up the `windows,linux,macOS` matrix if the CLI hadn't changed

2022-09-18 13:34 UTC, erezrokah commented on cli/integration_tests/gen_test.go
> +			require.Equal(t, plugin.kind, config.Kind)
This is a sanity check. We shouldn't be testing the whole parsing here

2022-09-18 13:35 UTC, erezrokah commented on cli/integration_tests/sync_test.go
> +func addDestination(t *testing.T, configFile string) {
We should be able to remove this once https://github.com/cloudquery/cloudquery/pull/1847 is merged

2022-09-18 15:34 UTC, erezrokah commented
OK so I found https://github.com/cloudquery/cloudquery/blob/9e3ace775da2d600968ef4275e9e0013d4dfd825/cli/cmd/generate_test.go#L70 and https://github.com/cloudquery/cloudquery/blob/9e3ace775da2d600968ef4275e9e0013d4dfd825/cli/cmd/sync_test.go#L9 so I'll merge the too.
The separation to integration tests is so we can run them on Windows/MacOS too

2022-09-18 16:16 UTC, erezrokah commented
OK so this PR improves on the current test by:
1. Runs each test in a separate isolated directory
2. Runs the CLI via an external process closer to how the user runs int
3. Separate the integration tests from the unit tests and runs them on a multiple OS matrix

2022-09-18 16:22 UTC, erezrokah commented
Looks like the CLI v2 doesn't work on Windows https://github.com/cloudquery/cloudquery/actions/runs/3077812862/jobs/4972939978#step:7:42

2022-09-18 18:38 UTC, yevgenypats commented
> OK so this PR improves on the current tests by:
> 
> 1. Runs each test in a separate isolated directory so easy to add more scenarios
> 2. Runs the CLI via an external process closer to how the user runs it
> 3. Separate the integration tests from the unit tests and runs them on a multiple OS matrix

Im not a big fan of running this test as an external process as it makes testing good and bad test cases much hard as it will involve stdout output. I specifically built the cobra in such way that it should be possible to do so via `NewRootCmd` which is the main entry point so there shouldn't be any difference between this and an external process.

2022-09-18 18:50 UTC, erezrokah commented
> I specifically built the cobra in such way that it should be possible to do so via `NewRootCmd` which is the main entry point so there shouldn't be any difference between this and an external process.

Is there a way to run isolated tests in a temp directory and not in the CWD? That should allow us to reduce dependencies between tests and run tests in parallel.

Also I think testing stdout is not necessarily bad in the case of CLIs as that's what the user experiences. We can leverage snapshot testing on the CLI output to avoid the need to parse the output.
Probably better to discuss via a Zoom call :)

2022-09-18 21:42 UTC, yevgenypats commented
> > I specifically built the cobra in such way that it should be possible to do so via `NewRootCmd` which is the main entry point so there shouldn't be any difference between this and an external process.
> 
> Is there a way to run isolated tests in a temp directory and not in the CWD? That should allow us to reduce dependencies between tests and run tests in parallel.
> 
> Also I think testing stdout is not necessarily bad in the case of CLIs as that's what the user experiences. We can leverage snapshot testing on the CLI output to avoid the need to parse the it. Probably better to discuss via a Zoom call :)

Yeah I think it should be possible to do in separate directories. Also, Im not a big fan of snapshot testing :) https://medium.com/@sapegin/whats-wrong-with-snapshot-tests-37fbe20dfe8e
but sure let's do zoom 📞

2022-09-19 07:47 UTC, erezrokah commented on .github/workflows/test_unit.yml
> +        run: go test -v ./... --tags unit
Good point. I think I'll take the suggestion from https://github.com/cloudquery/cloudquery/issues/1803 to run all tests on all OSs

2022-09-19 07:47 UTC, hermanschaaf commented on cli/integration_tests/gen_test.go
> +			require.Equal(t, plugin.kind, config.Kind)
```suggestion
			// sanity check only; we shouldn't be testing the full config here
			require.Equal(t, plugin.kind, config.Kind)
```

2022-09-19 08:07 UTC, erezrokah commented
> Yeah I think it should be possible to do in separate directories. Also, Im not a big fan of snapshot testing :) https://medium.com/@sapegin/whats-wrong-with-snapshot-tests-37fbe20dfe8e

I'm familiar with the article and agree that in most cases (like testing Web apps with Jest) they don't provide much value.
I do think for CLIs they can provide benefits but lets discuss separately as it's out of scope for this PR and for v2 initial iteration. Opened a separate issue to discuss https://github.com/cloudquery/cloudquery/issues/1860

2022-09-19 10:32 UTC, hermanschaaf commented on cli/cmd/generate_test.go
> +	tmpdir := t.TempDir()
Oh, nice, TIL that `testing.T` provides a `TempDir` function 🚀

2022-09-19 10:32 UTC, hermanschaaf approved these changes

2022-09-22 06:50 UTC, yevgenypats requested changes
Let's have a live discussion on the integration testing strategy?

2022-09-22 08:05 UTC, erezrokah commented on cli/cmd/doc_test.go
> +//go:build unit
This code it outdated per @hermanschaaf's comment. We don't have a separate between unit tests and integration tests.
This PR introduced a separate workflow that run only the CLI unit tests on Windows and MacOS (yet to be completed):
https://github.com/cloudquery/cloudquery/pull/1848/files#diff-0dbaaba16effff4896e9054770ab112bf49ae5b1e41a70915abafeef253b9ca7R31

2022-09-28 07:24 UTC, yevgenypats requested changes
Let's discuss live but see comment here - https://github.com/cloudquery/cloudquery/issues/1860#issuecomment-1259419465 

I don't think that we need to test/maintain output snapshot/predictability of a CLI

2022-09-28 08:42 UTC, erezrokah commented
> I don't think that we need to test/maintain output snapshot/predictability of a CLI

To clarify, this PR does not introduce snapshot testing. I adds a workflow to run exiting CLI tests on Windows and Mac and changes the CLI tests so they can be executed in a temporary directory and not the CWD of the tests

2022-10-02 14:07 UTC, erezrokah commented
Replaced by https://github.com/cloudquery/cloudquery/pull/2204

2022-10-02 14:07 UTC, closed without merging