chore: Merge Build,Lint and Unit Tests workflows
cloudquery/cloudquery pull request #2112
Opened 2022-09-28 11:39 UTC by erezrokah

#### Summary

Per our internal discussion to reduce the number of status checks per PR

2022-09-28 11:45 UTC, erezrokah commented on .github/workflows/test_unit.yml
> +    services:
This was removed in https://github.com/cloudquery/cloudquery/pull/2074.

I suggest we keep it here at least until we ensure all CI passes without it

2022-09-28 11:48 UTC, hermanschaaf approved these changes

2022-09-28 11:48 UTC, yevgenypats requested changes
Let's hold off with that a bit. I would like to try a backward solution that I'll share today/tomorrow where there is one check that is the required check and it waits for the checks to pass based on the same logic that we already have via changed files.

2022-09-28 12:27 UTC, erezrokah commented
@yevgenypats maybe merge this so at least we have a passing CI :) We can always do another PR with your change

2022-09-29 07:44 UTC, erezrokah commented
Closing for https://github.com/cloudquery/cloudquery/pull/2093

2022-09-29 07:44 UTC, closed without merging