Help message on subcommand
cloudquery/cloudquery pull request #239
Opened 2021-11-02 17:06 UTC by spangenberg

Fixes #235

2021-11-02 17:07 UTC, disq approved these changes

2021-11-02 20:33 UTC, roneli requested changes
<NVM>

2021-11-03 09:07 UTC, spangenberg commented
@roneli you're on the right branch?

```
dspangenberg@Daniels-MBP cloudquery %  go run . policy run -h
Executes a policy on CloudQuery database

Usage:
cloudquery policy run GITHUB_REPO [PATH_IN_REPO] [flags]

Examples:

  # Download & Run official policy from Policy Hub
  cloudquery policy run aws-cis-1.2.0

  # Download & Run official policy from Policy Hub (equivalent to the above)
  # Official policies hosted at https://github.com/cloudquery-policies
  cloudquery policy run cloudquery-policies/aws-cis-1.2.0

  # Run without downloading
  cloudquery policy download aws-cis-1.2.0
  cloudquery policy run --skip-download aws-cis-1.2.0

  # See https://hub.cloudquery.io for additional policies.

Flags:
  -h, --help              help for run
      --output string     Generates a new file at the given path with the output
      --skip-download     Skip downloading the policy repository
      --skip-versioning   Skip policy versioning and use latest files
      --stop-on-failure   Stops the execution on the first failure
      --sub-path string   Forces the policy run command to only execute this sub policy/query

Additional help topics:
Use "cloudquery options" for a list of global CLI options.
```

2021-11-03 09:10 UTC, roneli approved these changes
LGTM

2021-11-03 09:14 UTC, merged