feat: Add Support for ECR Registries
cloudquery/cloudquery pull request #2602
Opened 2022-10-10 16:10 UTC by bbernays

#### Summary

- Added table for `aws_ecr_registries`
- Added table for `aws_ecr_registry_policies`

2022-10-10 16:47 UTC, disq commented
I think the `validateResource` method in `source_testing.go` needs an update, but not sure how.
https://pkg.go.dev/github.com/aws/aws-sdk-go/service/ecr#GetRegistryPolicyOutput

2022-10-11 14:22 UTC, bbernays commented on plugins/source/aws/resources/services/ecr/registry_policies_fetch.go
> +	output, err := svc.GetRegistryPolicy(ctx, &ecr.GetRegistryPolicyInput{})
https://github.com/cloudquery/cloudquery/issues/2631

2022-10-11 14:37 UTC, hermanschaaf requested changes

2022-10-11 14:47 UTC, bbernays commented on plugins/source/aws/codegen/recipes/ecr.go
> +			Multiplex:  `client.AccountMultiplex`,
Great catch! I had the same idea in the beginning then second guessed myself...

2022-10-11 15:18 UTC, bbernays commented on plugins/source/aws/codegen/recipes/ecr.go
> +				defaultRegionalColumns,
Done. Added `defaultRegionalColumnsPK` that adds the PK attribute

2022-10-11 15:28 UTC, hermanschaaf approved these changes
Nice 👍

2022-10-12 13:45 UTC, merged