doc: Change default write_mode to 'overwrite-delete-stale'
cloudquery/cloudquery pull request #2675
Opened 2022-10-12 10:41 UTC by shimonp21

#### Summary

2022-10-12 12:13 UTC, hermanschaaf approved these changes

2022-10-12 12:36 UTC, disq approved these changes

2022-10-12 12:36 UTC, disq commented on website/pages/docs/reference/destination-spec.md
> +                             are no longer present in the cloud.
extra padded newline?

2022-10-13 17:33 UTC, yevgenypats requested changes
Is it the default right now in the SDK? If not I suggest to wait before we make it a default, as Im not sure which default is better the one that doesn't delete data by default or the one that does without any warning.

2022-10-14 09:34 UTC, shimonp21 commented on website/pages/docs/reference/destination-spec.md
> +                             are no longer present in the cloud.
looks OK after MD does it's thing :)

2022-10-14 09:53 UTC, yevgenypats approved these changes

2022-10-14 09:54 UTC, merged