fix(cli): Add flag to disable log console color
cloudquery/cloudquery pull request #2812
Opened 2022-10-13 16:06 UTC by erezrokah

#### Summary

Related to https://github.com/cloudquery/cloudquery/issues/2644.
Since the default is to have log color, it makes sense to have a `--no-color` flag instead of `--color`. I added one in a backwards compatible way. Also I think `auto` never really worked.

2022-10-13 16:08 UTC, erezrokah commented on website/pages/docs/reference/cli/cloudquery.md
> -      --color string           Enable colorized output (on, off, auto) (default "auto")
Since we marked the flag as deprecated it's removed from the help, but still works

2022-10-13 17:20 UTC, yevgenypats commented
Giving it a bit more thought, I think we need to skip color all together and only do without colors.

ELT workloads produces tons of logs so no one is really going through them through the terminal.
By disabling color by default I think we will insure the correct behaviour out of the box and prevent confusion and more flags. 

I think our CLI is more of very slim worker rather then a UI or something like this so I think it makes sense to avoid colors completely, which causes issues in production environments. wdyt ?

2022-10-13 17:20 UTC, yevgenypats requested changes
Giving it a bit more thought, I think we need to skip color all together and only do without colors.

ELT workloads produces tons of logs so no one is really going through them through the terminal.
By disabling color by default I think we will insure the correct behaviour out of the box and prevent confusion and more flags.

I think our CLI is more of very slim worker rather then a UI or something like this so I think it makes sense to avoid colors completely, which causes issues in production environments. wdyt ?

2022-10-16 07:35 UTC, erezrokah commented
> Giving it a bit more thought, I think we need to skip color all together and only do without colors.
> 
> ELT workloads produces tons of logs so no one is really going through them through the terminal. By disabling color by default I think we will insure the correct behaviour out of the box and prevent confusion and more flags.
> 
> I think our CLI is more of very slim worker rather then a UI or something like this so I think it makes sense to avoid colors completely, which causes issues in production environments. wdyt ?

Good point, I kept the deprecation with a message that console logs are always colorless

2022-10-16 07:43 UTC, yevgenypats approved these changes

2022-10-16 08:16 UTC, merged