Telemetry improvements
cloudquery/cloudquery pull request #301
Opened 2021-11-26 14:57 UTC by disq

- [x] Instrument ConsoleClient
- [ ] Collect fetch statistics / resource counts / partial errors
- [ ] Log policy names? Only if cq policies
- [ ] ...

2021-11-29 14:41 UTC, disq commented
I would not merge this before tagging/releasing telemetry 1.0

2021-11-30 14:39 UTC, roneli requested changes
Some review comments, would also add to error telemetry the severity/type.

2021-11-30 14:59 UTC, disq commented on internal/telemetry/error.go
> +	span.SetStatus(codes.Error, err.Error())
Inverting the if would look like:
`if d, ok := span.(debugModer); !ok || !d.DebugMode() {`
confusing don't you think?

2021-11-30 20:50 UTC, roneli approved these changes
Perfect change imho

2021-11-30 20:54 UTC, merged