feat(blog): CloudQuery with GCP and Kubernetes
cloudquery/cloudquery pull request #3085
Opened 2022-10-20 09:30 UTC by SCKelemen

Blog Post
Getting Started with GCP and Kubernetes

Checklist

- [x] Author profile
- [ ] Author image
- [x] Blog post
- [ ] Post images
- [x] Blog metadata
- [ ] Checks pass

2022-10-20 11:15 UTC, erezrokah commented
Looks like the Website build is failing due to a missing image:
https://vercel.com/cloudquery/cloudquery-web/J2n2tuk6bYf7ZkM22LxCWw6mrYEp

`Module not found: Can't resolve '../img/estore.jpg' in '/vercel/path0/website/pages/blog'`

2022-10-20 15:28 UTC, SCKelemen commented
I ran the images through tinypng, but they're still >250kb.

2022-10-20 16:20 UTC, erezrokah commented on website/pages/blog/getting-started-with-gcp-and-kubernetes.md
> +To create a cluster, you'll need the project name, the GCP region, and a name for your cluster.
```suggestion
To create a cluster, you'll need the project name, the GCP region, add a name for your cluster.
```

Not sure if I got this right

2022-10-20 16:22 UTC, erezrokah commented on website/pages/blog/getting-started-with-gcp-and-kubernetes.md
> +${project-name} = cq-kelemen
Can we wrap this with a code block (```)? I think it's making Nextra (our build framework) angry

2022-10-20 16:44 UTC, yevgenypats requested changes
Good stuff. I especially liked to `changeds-to-k8s-auth` as it's a bit more advanced.

I think we need to turn this blog just into `k8s` recipe under https://www.cloudquery.io/docs/recipes/overview 

I don't think how to run k8s is needed here due to if someone needs to use cq then they already familiar with k8s and if not then I think it's a whole another blog of intro to k8s which can be very long or even a series of blogs. so would keep it just as a recipe for gcp+k8s and this will also include the `changes-to-kubernetes-auth` potentially as a section/note

2022-10-31 18:03 UTC, yevgenypats approved these changes

2022-10-31 18:04 UTC, merged