doc: Try to make it clearer that names must be unique
cloudquery/cloudquery pull request #3276
Opened 2022-10-28 12:25 UTC by shimonp21

#### Summary

2022-10-28 13:59 UTC, disq requested changes
LGTM but one typo

2022-10-28 13:59 UTC, disq commented on website/pages/docs/advanced-topics/running-cloudquery-in-parallel.mdx
> +If the configurations overlap, the behavior is unexpeceted, and the database may contain duplicate rows.
```suggestion
If the configurations overlap, the behavior is unexpected, and the database may contain duplicate rows.
```

2022-10-31 08:54 UTC, disq approved these changes

2022-10-31 09:28 UTC, yevgenypats approved these changes

2022-10-31 09:29 UTC, merged