Feat/aws document db resources2
cloudquery/cloudquery pull request #3277
Opened 2022-10-28 12:41 UTC by amanenk

#### Summary

2022-10-31 20:22 UTC, yevgenypats approved these changes

2022-11-01 20:45 UTC, bbernays requested changes

2022-11-01 20:45 UTC, bbernays commented on plugins/source/aws/resources/services/docdb/event_subscriptions_fetch.go
> +	input := &docdb.DescribeEventSubscriptionsInput{}
This needs to have a filter so that it only finds subscriptions for docdb

2022-11-01 20:45 UTC, bbernays commented on plugins/source/aws/resources/services/docdb/event_subscriptions_fetch.go
> +	input := &docdb.DescribeEventSubscriptionsInput{}
Like this: https://github.com/cloudquery/cloudquery/blob/c9c1e4cf0d3c5175799a21829afefd712f322aad/plugins/source/aws/resources/services/neptune/event_subscriptions_fetch.go#L17

2022-11-03 16:25 UTC, disq approved these changes

2022-11-03 16:32 UTC, bbernays approved these changes

2022-11-03 17:40 UTC, merged