Integrate Sentry
cloudquery/cloudquery pull request #342
Opened 2021-12-14 12:32 UTC by disq

What more do we need?

2021-12-14 13:33 UTC, spangenberg reviewed
LGTM

2021-12-14 15:20 UTC, yevgenypats submitted a review, later dismissed
Where is the opt-out flag?

2021-12-14 15:32 UTC, disq commented
> Where is the opt-out flag?

oops. added.

2021-12-14 17:01 UTC, spangenberg approved these changes

2021-12-15 08:15 UTC, roneli requested changes
Would also suggest to do some manual tests like running AWS provider with bad credentials

Also write some tests for example test provider and see that errors get captured and sent.

For AWS provider I would test that the no creds are leaked, they shouldn't but just to double check.

2021-12-15 08:15 UTC, roneli commented on pkg/client/client.go
> +			}
```suggestion
			if e.Severity() != diag.ERROR {
			  continue
			}
				d := e.Description()
				sentry.CaptureException(fmt.Errorf("%s: %s: %s: %s: %s", ps.ProviderName, e.Type().String(), d.Resource, d.Summary, d.Detail))
```

2021-12-15 08:15 UTC, roneli commented on pkg/client/client.go
> +	reportFetchSummaryStats(response.ProviderFetchSummary)
```suggestion
	reportFetchSummaryErrors(response.ProviderFetchSummary)
```

2021-12-15 08:15 UTC, roneli commented on pkg/client/client.go
> +	reportFetchSummaryStats(response.ProviderFetchSummary)
I think you could probably combine both methods to reduce the looping, wdyt?

2021-12-15 11:13 UTC, roneli approved these changes
LGTM, minor nit

2021-12-15 11:13 UTC, roneli commented on internal/telemetry/error.go
>  	//  TODO for fetch get table name / error type
we do this no with resource name etc' so we can remove this TODO

2021-12-15 12:13 UTC, merged