feat(cli): Validate plugins gRPC protocol version
cloudquery/cloudquery pull request #3657
Opened 2022-11-06 12:00 UTC by erezrokah

#### Summary

Fixes https://github.com/cloudquery/cloudquery/issues/3628

Examples:
![image](https://user-images.githubusercontent.com/26760571/200169357-b9d891a9-72fd-485a-8609-17f6fe2c6f76.png)

![image](https://user-images.githubusercontent.com/26760571/200169392-71e92582-951c-4b20-98b7-7784a7637091.png)

2022-11-06 12:02 UTC, erezrokah commented on cli/cmd/sync.go
> +		if destProtocolVersion != expectedProtocolVersion {
Initially I thought about trying to be more specific (e.g. telling the user to update only the destination or only the source), but that probably has a ton of edge cases. For example what if we have protocol version 3, then we need to start to check ranges 🙃

2022-11-06 12:04 UTC, disq approved these changes

2022-11-06 13:15 UTC, yevgenypats requested changes
I think let's wait with that. it should be done on the server side where there are still few culprits before we can take care of that.

Mostly we need to start versioning SDK with v1, v2 and making protobuf versioned as well (the package name in prtobouf) - this way v1 will never be able to connect to an uncompatible version.

2022-11-06 13:45 UTC, erezrokah commented
> I think let's wait with that. it should be done on the server side where there are still few culprits before we can take care of that.
> 
> Mostly we need to start versioning SDK with v1, v2 and making protobuf versioned as well (the package name in prtobouf) - this way v1 will never be able to connect to an uncompatible version.

We can always remove this logic when we have server side validation. This is mostly needed for users updating to the latest CLI version with the type system changes (we've seen reports on Discord with the error mentioned in the bug)

2022-11-06 13:45 UTC, erezrokah commented
Also the tests are blocked by https://github.com/cloudquery/plugin-sdk/issues/351 but we can comment them

2022-11-06 14:34 UTC, erezrokah commented
PR to fix the Windows bug https://github.com/cloudquery/plugin-sdk/pull/352

2022-11-06 14:54 UTC, yevgenypats commented
Im just working on this atm in my sdk pr https://github.com/cloudquery/plugin-sdk/pull/348 so this will create more work for me reviewing and then removing the logic. let's hold off

2022-11-16 15:47 UTC, yevgenypats commented
Let's close this?

2022-11-16 16:20 UTC, closed without merging