fix(aws): Skip resource on NotFound PreResourceResolver
cloudquery/cloudquery pull request #4376
Opened 2022-11-11 10:10 UTC by disq

Needs https://github.com/cloudquery/plugin-sdk/pull/401 to work. More resources to come.

2022-11-11 12:23 UTC, candiduslynx submitted a review, later dismissed

2022-11-11 12:23 UTC, candiduslynx commented on plugins/source/aws/go.mod
> +replace github.com/cloudquery/plugin-sdk => ../../../../plugin-sdk
needs to be updated after https://github.com/cloudquery/plugin-sdk/pull/401

2022-11-11 15:48 UTC, yevgenypats requested changes
Why not just return the error (and remove the dead code checking for not-found) so errors will be logged in unified format?

2022-11-11 19:23 UTC, disq commented
> Why not just return the error (and remove the dead code checking for not-found) so errors will be logged in unified format?

Sure, done. All the regular resolvers still have notfound checks, maybe another, larger PR for those in the future as well.

2022-11-13 08:48 UTC, erezrokah approved these changes

2022-11-13 11:20 UTC, erezrokah approved these changes

2022-11-13 13:20 UTC, merged