feat: Added checking of finished fetches before running policy
cloudquery/cloudquery pull request #444
Opened 2022-01-26 12:42 UTC by amanenk

- added logic that checks for fetch summaries before running policy
- fetch summary client is moved to separate package to prevent import cycle

2022-01-31 09:26 UTC, disq commented on pkg/client/fetch_summary/fetch_summary.go
> +	err = pgxscan.Select(ctx, c.db, &data, sql)
If selecting a single row, could do `.Get` instead. No rows would return an error (pgx.ErrNoRows but wrapped)

But maybe get latest row per version? Not sure

2022-01-31 09:41 UTC, disq commented on pkg/client/client.go
> +
Also, rogue line

2022-01-31 14:06 UTC, disq commented on pkg/client/fetch_summary/fetch_summary.go
> +		if err == pgx.ErrNoRows {
Should use `errors.Is` I think, not sure if this will work directly.

2022-01-31 17:13 UTC, disq requested changes
nits about naming things

2022-01-31 17:13 UTC, disq commented on pkg/client/fetch_summary/fetch_summary.go
> +type FetchSummaryClient struct {
`Client` maybe?

2022-01-31 17:13 UTC, disq commented on pkg/client/fetch_summary/fetch_summary.go
> +func NewFetchSummaryClient(db schema.QueryExecer) *FetchSummaryClient {
```suggestion
func New(db schema.QueryExecer) *Client {
```

or `NewClient`

2022-01-31 17:13 UTC, disq commented on pkg/client/fetch_summary/fetch_summary.go
>  type FetchSummary struct {
Name it `Data`?

2022-01-31 17:13 UTC, disq commented on pkg/client/fetch_summary/fetch_summary_test.go
> +
rogue line

2022-01-31 17:13 UTC, disq commented on pkg/client/fetch_summary/fetch_summary.go
> +func (c *FetchSummaryClient) SaveFetchSummary(ctx context.Context, fs *FetchSummary) error {
Just `Save`?

2022-01-31 19:23 UTC, disq approved these changes
I still don't like `fetch_summary.FetchSummary` but OK otherwise

2022-02-01 08:13 UTC, roneli requested changes

2022-02-01 08:13 UTC, roneli commented on pkg/client/fetch_summary/fetch_summary.go
> +package fetch_summary
would call this package fetch and change inner types to Summary so it would be fetch.ResourceSummary etc'

2022-02-01 08:21 UTC, yevgenypats approved these changes
LGTM. one nit.

2022-02-01 08:21 UTC, yevgenypats commented on pkg/policy/execute_test.go
> +	db, err := sdkdb.New(context.Background(), hclog.NewNullLogger(), testDBConnection)
I'd add a way to override this.

2022-02-07 19:57 UTC, disq requested changes
You don’t need timescale migrations since the migrator always runs on the postgres dialect.

2022-02-08 11:11 UTC, disq requested changes

2022-02-08 11:11 UTC, disq commented on pkg/policy/execute.go
> +		return nil, fmt.Errorf("%s: %w, please run `cloudquery fetch` berfore running policy", policy.Name, err)
```suggestion
		return nil, fmt.Errorf("%s: %w, please run `cloudquery fetch` before running policy", policy.Name, err)
```

2022-02-08 11:11 UTC, disq commented on pkg/policy/execute.go
> +			return fmt.Errorf("there is no finished fetches for provider %s", p.Type)
```suggestion
			return fmt.Errorf("could not find finished fetches for provider %s", p.Type)
```

2022-02-08 11:11 UTC, disq commented on pkg/client/meta_storage/fetch_summary.go
> +			return nil, errors.New("there is no successful fetch for requested provider")
```suggestion
			return nil, errors.New("could not find a completed fetch for requested provider")
```

2022-02-08 15:24 UTC, disq approved these changes

2022-03-22 17:02 UTC, merged