test: Validate Go Releaser ZIP files
cloudquery/cloudquery pull request #4468
Opened 2022-11-13 11:47 UTC by erezrokah

#### Summary

2022-11-13 15:19 UTC, yevgenypats requested changes
Let's hold off a bit with this, I'd like to give a try to see if there is a way to simplify this as seems complexity is starting to grow around our workflows.

2022-11-13 16:08 UTC, erezrokah commented
Per @yevgenypats suggestion I'm going to see if we can move this validation to the Go Releaser configuration file

2022-11-13 16:53 UTC, erezrokah commented
@yevgenypats see different approach in https://github.com/cloudquery/cloudquery/pull/4468/commits/b9869b7208066ee3cfd2855ea6fed65d44be111b

2022-11-14 08:46 UTC, candiduslynx commented on plugins/.goreleaser.yaml
> +    - cmd: unzip -o {{ .Var.binary }}_windows_amd64.zip
Will we add windows_arm64 as well?

2022-11-15 16:23 UTC, yevgenypats approved these changes

2022-11-15 16:58 UTC, merged