fix: Use provider source
cloudquery/cloudquery pull request #458
Opened 2022-01-31 18:06 UTC by zagronitay

2022-01-31 19:22 UTC, disq reviewed
LGTM

2022-01-31 19:22 UTC, disq commented on cmd/init.go
> +			return fmt.Errorf("cloud not parse requested provider")
```suggestion
			return fmt.Errorf("could not parse requested provider")
```

2022-02-01 08:08 UTC, roneli requested changes
LGTM, minor nit comment

2022-02-01 08:08 UTC, roneli commented on pkg/plugin/registry/hub.go
> +	organization, providerName, err := ParseProviderName(requestedSource)
nit: make this a function of h.Hub

2022-02-01 13:37 UTC, roneli approved these changes
LGTM

2022-02-01 13:37 UTC, merged