feat(aws): Add ssoadmin permission_sets
cloudquery/cloudquery pull request #4817
Opened 2022-11-18 20:39 UTC by jhudson10x

#### Summary

Add support for SSOAdmin permission sets

2022-11-20 15:59 UTC, bbernays requested changes
This looks good can you run:
- `make lint`: to run the standard linting tool over the plugin
- `make gen-docs`: to regenerate all of the docs for the plugin

2022-11-20 15:59 UTC, bbernays commented on plugins/source/aws/resources/services/ssoadmin/account_assignments_fetch.go
> +	}
```suggestion
	cl := meta.(*client.Client)
	svc := client.Services().Ssoadmin
	permission_set_arn := parent.Item.(*types.PermissionSet).PermissionSetArn
	instance_arn := parent.Parent.Item.(types.InstanceMetadata).InstanceArn
	config := ssoadmin.ListAccountAssignmentsInput{
		AccountId:        &cl.AccountID,
		InstanceArn:      instance_arn,
		PermissionSetArn: permission_set_arn,
	}
```

2022-11-20 15:59 UTC, bbernays commented on plugins/source/aws/resources/services/ssoadmin/permission_sets_fetch.go
> +	svc := client.Services().Ssoadmin
```suggestion
	cl := meta.(*client.Client)
	svc := cl.Services().Ssoadmin
```

2022-11-21 17:39 UTC, bbernays approved these changes

2022-11-21 22:30 UTC, disq requested changes
Thanks for the submission! I think I would prefer `Description`s to be linked to type descriptions rather than the actual API calls that were used to extract them. Just for consistency and ease of use.

2022-11-21 22:30 UTC, disq commented on plugins/source/aws/codegen/recipes/ssoadmin.go
> +			Description: "https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_ListInstances.html",
```suggestion
			Description: "https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_InstanceMetadata.html",
```

2022-11-21 22:30 UTC, disq commented on plugins/source/aws/codegen/recipes/ssoadmin.go
> +			Description:         "https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DescribePermissionSet.html",
```suggestion
			Description:         "https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_PermissionSet.html",
```

2022-11-21 22:30 UTC, disq commented on plugins/source/aws/codegen/recipes/ssoadmin.go
> +			Description: "https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_ListAccountAssignments.html",
```suggestion
			Description: "https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_AccountAssignment.html",
```

2022-11-21 22:46 UTC, jhudson10x commented
I committed @disq suggestions but `make gen-docs` doesn't seem to be updating the generated documentation with the new descriptions.

2022-11-22 13:19 UTC, disq approved these changes
LGTM, not sure about the `gen-docs` issue

2022-11-22 20:39 UTC, jhudson10x commented
Figured it out from the pipeline failures. I had to run `make gen` before running `make gen-docs` again.

2022-11-23 10:54 UTC, merged