feat: Datadog plugin
cloudquery/cloudquery pull request #5096
Opened 2022-11-25 12:47 UTC by amanenk

#### Summary

closes #4794

2022-11-25 14:24 UTC, hermanschaaf requested changes
Nice! I know this is still in draft, but I did a quick read-through and left some comments with some things for us to remember before merging. Looks great so far 👍

2022-11-25 14:24 UTC, hermanschaaf commented on .github/workflows/source_datadog.yml
> +name: Source Plugin AWS Workflow
```suggestion
name: Source Plugin Datadog Workflow
```

2022-11-25 14:24 UTC, hermanschaaf commented on plugins/source/datadog/client/client.go
> +		return nil, errors.New("error no datadog accounts configured")
```suggestion
		return nil, errors.New("no datadog accounts configured")
```

2022-11-25 14:24 UTC, hermanschaaf commented on plugins/source/datadog/client/client.go
> +	// For now, going to do that in the resources. Still not sure how multiplexers work
Is this comment still correct? Looks like we are using multiplexers for accounts

2022-11-25 14:24 UTC, hermanschaaf commented on plugins/source/datadog/client/spec.go
> +	Accounts []Account `hcl:"accounts,block"`
```suggestion
	Accounts []Account `json:"accounts"`
```

2022-11-25 14:24 UTC, hermanschaaf commented on plugins/source/datadog/codegen/recipies/base.go
> +package recipies
```suggestion
package recipes
```

This package should be renamed to `recipes` to fix the typo

2022-11-25 14:24 UTC, hermanschaaf commented on plugins/source/datadog/codegen/recipies/base.go
> +	"github.com/iancoleman/strcase"
Let's use our `caser` library from plugin-sdk everywhere (I realize this was copy-pasted from somewhere else, but we'll get round to fixing those other places eventually too)

2022-11-25 14:24 UTC, hermanschaaf commented on plugins/source/datadog/main.go
> +const sentryDSN = "https://99f66f1a627f48deb66e49a25d6028a6@o1396617.ingest.sentry.io/6747628"
```suggestion
const sentryDSN = "https://a0c2570b96264748a6759bb62e8cdef5@o1396617.ingest.sentry.io/4504220208267264"
```

Here is a new DSN to use for Datadog

2022-11-25 14:24 UTC, hermanschaaf commented on plugins/source/datadog/scripts/regenerate-changed-directories.sh
> +set -x
We don't need this script anymore, it can be deleted

2022-11-25 14:24 UTC, hermanschaaf commented on plugins/source/datadog/scripts/terraform-apply-all.sh
> +#!/usr/bin/env bash
This too, and everything else in this directory (probably)

2022-11-29 13:13 UTC, erezrokah requested changes
Looks great @amanenk, I think it's only missing updating the docs in our Website (we moved them recently from GitHub).

Once this is released we should add it to https://github.com/cloudquery/cloudquery/blob/0e4b8dc53358388f8a1e61cad8ae8a1ab2f52342/website/pages/docs/plugins/sources/overview.mdx as `Preview`

2022-11-29 13:13 UTC, erezrokah commented on plugins/source/datadog/README.md
> +# Datadog Plugin
I think we'll need to move this to the Website, see example in https://github.com/cloudquery/cloudquery/tree/main/plugins/source/azure#readme
https://github.com/cloudquery/cloudquery/tree/0e4b8dc53358388f8a1e61cad8ae8a1ab2f52342/website/pages/docs/plugins/sources/azure

and changes in https://github.com/cloudquery/cloudquery/pull/5104

2022-11-30 08:53 UTC, erezrokah approved these changes
Thanks for the follow up @amanenk. I added another comment and the Vercel build failure should be fixed in https://github.com/cloudquery/cloudquery/pull/5170

2022-11-30 08:53 UTC, erezrokah commented on plugins/source/datadog/README.md
> +- [Contribution Guide](./CONTRIBUTING.md)
```suggestion
```

I don't think we have a contributing guide yet

2022-11-30 15:20 UTC, hermanschaaf approved these changes

2022-11-30 15:27 UTC, merged