feat: Adds datadog plugin resources
cloudquery/cloudquery pull request #5192
Opened 2022-11-30 15:28 UTC by amanenk

#### Summary

2022-11-30 16:39 UTC, erezrokah approved these changes
🚀

2022-11-30 16:44 UTC, hermanschaaf requested changes
Looks good, that's a lot of resources! I had a brief look through, and just had the one question about PKs.

2022-11-30 16:44 UTC, hermanschaaf commented on plugins/source/datadog/docs/tables/datadog_dashboard_lists.md
> +|id (PK)|Int|
Is `id` guaranteed to be unique across accounts, or should `account_name` be part of the PK here? (same question for other tables) It's probably safer to include `account_name` in the PK, so we don't risk overwriting rows of other accounts?

2022-12-01 13:28 UTC, hermanschaaf approved these changes

2022-12-01 13:29 UTC, hermanschaaf commented
Looks like the table docs will just need to be regenerated with the new (nested lists) format.

2022-12-01 13:33 UTC, erezrokah commented
/gen sha=7e7a4ecd6e109e576d7ce037e30da4698a611b83 source=datadog

2022-12-01 13:37 UTC, erezrokah commented
/gen sha=7e7a4ecd6e109e576d7ce037e30da4698a611b83 plugin=datadog

2022-12-01 13:53 UTC, erezrokah commented
/gen sha=a6d78ad5b656c348f6dafbaefda95997fda3ced1 plugin=datadog

2022-12-01 13:57 UTC, merged