feat: Support go native git as fallback for git binary
cloudquery/cloudquery pull request #547
Opened 2022-03-22 10:32 UTC by roneli

2022-03-22 15:28 UTC, disq requested changes

2022-03-22 15:28 UTC, disq commented on internal/getmodules/get_git.go
> +	getter.GitGetter
Why embed both Getters in the struct? I would give them names so their methods aren't implicitly used/made available by something like `getmodules.GitGetter.SomeMethodInHashiGitGetter()`

```
type GitGetter struct {
	hashiImpl getter.GitGetter
	goImpl GoGitGetter
}
```
or something like that

2022-03-28 08:31 UTC, roneli commented on internal/getmodules/go_git.go
> +		return "master"
I left it master as that is the original code, I can change it to main, was thinking that as well, wdyt?

2022-03-28 08:38 UTC, disq commented on internal/getmodules/go_git.go
> +		return "master"
That's what the suggestion is all about :)

2022-06-09 07:09 UTC, yevgenypats commented
Can we close this as we are not going to support it soon?

2022-06-19 12:08 UTC, erezrokah commented
Closing as stale, if I got this wrong please let me know and I'll re-open

2022-06-19 12:08 UTC, closed without merging