feat(website): Document Homebrew specific version
cloudquery/cloudquery pull request #5482
Opened 2022-12-07 12:37 UTC by erezrokah

#### Summary

The convention in Homebrew is to use `@<version>` without the `v`, so this required a bit more changes.
Instead of adding to the existing code block, we can also use a callout for it to get more visibility (I'm not sure we want that)

2022-12-07 12:43 UTC, yevgenypats requested changes
Why do we need full and trimmed? can we have just one?

2022-12-07 12:45 UTC, erezrokah commented
> Why do we need full and trimmed? can we have just one?

We use `v` in our tags https://github.com/cloudquery/cloudquery/releases/tag/cli-v2.0.25, and the naming convention in Homebrew is to not have `v`, so if we need to chose I think we'll need to change our tags

2022-12-07 12:46 UTC, erezrokah commented
We can also do something like `vVERSION_CLI` in the docs

2022-12-07 12:58 UTC, erezrokah commented on website/components/mdx/_download-linux.mdx
> -curl -L https://github.com/cloudquery/cloudquery/releases/download/VERSION_CLI/cloudquery_linux_amd64 -o cloudquery
Not having `cli-` prefix here is a bug also on https://www.cloudquery.io/

2022-12-07 13:05 UTC, erezrokah commented on website/components/mdx/_download-linux.mdx
> -curl -L https://github.com/cloudquery/cloudquery/releases/download/VERSION_CLI/cloudquery_linux_amd64 -o cloudquery
Extracted this to a separate PR https://github.com/cloudquery/cloudquery/pull/5484

2022-12-08 09:37 UTC, yevgenypats approved these changes

2022-12-08 09:38 UTC, merged