refactor: Rename firebase client type
cloudquery/cloudquery pull request #622
Opened 2022-05-02 08:39 UTC by erezrokah

Follow up on https://github.com/cloudquery/cloudquery/pull/618

2022-05-02 09:27 UTC, disq approved these changes

2022-05-02 10:08 UTC, roneli requested changes
Move this under registry, moreover merge this after #623  is merged.

2022-05-03 11:57 UTC, erezrokah commented
@roneli rebased the PR

2022-05-03 14:05 UTC, roneli approved these changes
I think this should maybe move to hub package as its only related to it, maybe in a separate PR.

2022-05-03 14:07 UTC, merged