fix(postgres): Error new PK column
cloudquery/cloudquery pull request #6749
Opened 2023-01-12 10:30 UTC by erezrokah

#### Summary

Related to https://github.com/cloudquery/cloudquery/issues/6600.

This changes the Postgres migration logic to fail when a new column is added and it's a PK.
This is the same as the SQLite plugin:
https://github.com/cloudquery/cloudquery/blob/bfd1494fa464f2cafa4b1d04bfd54ac4726319ad/plugins/destination/sqlite/client/migrate.go#L93

I think we can improve this as only error if the table exists and is not empty as for empty tables this shouldn't be an issue

2023-01-12 10:33 UTC, yevgenypats requested changes
The change looks good but before we do that I think we might want to introduce the `--force` on the SDK/destination plugin level as we do change PKs quite a lot and most of the time I think it worked so I would worry of adding a blocker without introducing the easy workaround that most people basically use now by default?

2023-01-19 13:52 UTC, yevgenypats approved these changes

2023-01-19 14:07 UTC, erezrokah commented
I'll merge this after we add force migration support like we did in SQLite https://github.com/cloudquery/cloudquery/pull/6763

2023-01-25 07:55 UTC, erezrokah commented
Going to close this and do it once I add `migrate_mode: forced`

2023-01-25 07:55 UTC, closed without merging