feat(clickhouse): ClickHouse destination
cloudquery/cloudquery pull request #6982
Opened 2023-01-20 20:02 UTC by candiduslynx

Implements #6254

2023-01-30 13:07 UTC, disq commented on plugins/destination/clickhouse/README.md
> +# CloudQuery Microsoft SQL Server Destination Plugin
```suggestion
# CloudQuery ClickHouse Destination Plugin
```

2023-01-30 13:08 UTC, disq commented on plugins/destination/clickhouse/README.md
> +This destination plugin lets you sync data from any CloudQuery source to a Microsoft SQL Server database.
```suggestion
This destination plugin lets you sync data from any CloudQuery source to a ClickHouse database.
```

2023-01-30 13:08 UTC, disq commented on plugins/destination/clickhouse/README.md
> +- [User Guide](https://cloudquery.io/docs/plugins/destinations/mssql/overview)
```suggestion
- [User Guide](https://cloudquery.io/docs/plugins/destinations/clickhouse/overview)
```

2023-01-30 13:08 UTC, disq commented on release-please-config.json
> +      "component": "plugins-destination-mssql"
```suggestion
      "component": "plugins-destination-clickhouse"
```

2023-02-09 06:35 UTC, candiduslynx commented
> Looks good! I did only a very quick walkthrough. Can you update the migration code to work similarly to the new way in my pg PR - #7819
> 
> This should make migration faster and easier to understand across plugins.

@yevgenypats 
I can update, but ClickHouse won't allow multi-statement execution unless configured in the database, so it'll still be better off to be a simple bunch of statements per table executed one by one.
The migration is still really fast, so it's not a big concern here.

2023-02-09 07:08 UTC, yevgenypats commented
> > Looks good! I did only a very quick walkthrough. Can you update the migration code to work similarly to the new way in my pg PR - #7819
> > This should make migration faster and easier to understand across plugins.
> 
> @yevgenypats I can update, but ClickHouse won't allow multi-statement execution unless configured in the database, so it'll still be better off to be a simple bunch of statements per table executed one by one. The migration is still really fast, so it's not a big concern here.

There is no need for multi-statement? Can you query the catalog all at once? In any case even if you do multiple statement, can you transform the result of each table definition to `Table` and use the new helper functions like `AddedColumns` `ChangedColumns` and so on.

2023-02-09 07:09 UTC, candiduslynx commented
The reason why we store JSON as string: https://github.com/ClickHouse/ClickHouse/issues/46190

2023-02-09 12:05 UTC, candiduslynx commented
> can you transform the result of each table definition to `Table` and use the new helper functions like `AddedColumns` `ChangedColumns` and so on.

@yevgenypats we have several types mapping to `String` column type, so currently there's no way to distinguish the original cq type.

It might've worked if we were passing the mapping func from cq type to db column type to the comparison, so that we just check if the column in the database corresponds to the proper type based on the table definition, but, for now, not possible.

2023-02-13 08:22 UTC, yevgenypats requested changes
Same comment still stands. Any chance to normalize the ClickHouse table to the same CloudQuery schema tables instead of creating and maintaining the exact same struct and logic to detect schema changes?  See example - https://github.com/cloudquery/cloudquery/pull/7819

2023-02-13 11:43 UTC, yevgenypats requested changes
The diff logic looks better now.

Next major comment - Let's please drop the use of templating it's an overkill and an un-necessary abstraction because we are not building a library/query-builder here but rather a single destination plugin so queries are only used in that plugin.

2023-02-13 11:45 UTC, yevgenypats commented
> The diff logic looks better now.
> 
> Next major comment - Let's please drop the use of templating it's an overkill and an un-necessary abstraction because we are not building a library/query-builder here but rather a single destination plugin so queries are only used in that plugin.

Moreover, templates are notoriously hard to debug as you can't single-step it, so unless there is a really good reason we don't really want to use it and this case there isn't really a reason to use this instead of regular string builder or string concatination.

2023-02-14 09:12 UTC, hermanschaaf approved these changes
LGTM 👍  left some minor nice-to-have comments and a few questions

2023-02-14 09:12 UTC, hermanschaaf commented on plugins/destination/clickhouse/queries/test_data/col_add.sql
> +ALTER TABLE `table_name` ADD COLUMN `my_col` Int64
Let's rename this directory to the more standard `testdata` (no underscore) so that it gets ignored by the `go` tool.

2023-02-14 09:12 UTC, hermanschaaf commented on website/pages/docs/plugins/destinations/clickhouse/configuration.mdx
> +</Callout>
This callout should probably be lower down (below the example), it doesn't need to be the first thing on the page

2023-02-14 09:12 UTC, hermanschaaf commented on website/pages/docs/plugins/destinations/clickhouse/configuration.mdx
> +# ClickHouse destination plugin configuration reference
Let's move the contents of this file to the overview page and delete this one, there's no need to split them at this stage

2023-02-14 09:12 UTC, hermanschaaf commented on plugins/destination/clickhouse/queries/types.go
> +			res.Type = schema.TypeUUIDArray
We may want to have a default case here that panics, like in other switch statements

2023-02-14 10:22 UTC, candiduslynx commented on plugins/destination/clickhouse/client/unescape.go
> +func unescape(str string) string {
it was copied from MS SQL (that has tests for it), and it really should be a part of plugin-sdk per https://github.com/cloudquery/plugin-sdk/issues/622

2023-02-14 10:23 UTC, candiduslynx commented on plugins/destination/clickhouse/client/transform.go
> +	}
the driver still handles both types so no problem there.
However, I'll change the nil type for consistency

2023-02-14 10:24 UTC, hermanschaaf commented on plugins/destination/clickhouse/client/unescape.go
> +func unescape(str string) string {
Ah I see, but for now can we comment and copy the test here?

2023-02-14 10:42 UTC, disq approved these changes

2023-02-14 11:50 UTC, yevgenypats approved these changes
Great job!

2023-02-14 11:57 UTC, merged