fix(azure)!: Change `azure_compute_skus` PK from `id` to `(subscription_id, family, kind, name)`
cloudquery/cloudquery pull request #7267
Opened 2023-01-27 11:21 UTC by candiduslynx

2023-01-27 15:15 UTC, yevgenypats requested changes
Let's add id back as a pk to keep backward compatability

2023-01-27 15:16 UTC, candiduslynx commented
@yevgenypats 
> Let's add id back as a pk to keep backward compatibility

I don't think it's right, given that the table is most probably little used.
For starters, it's not present in any of the policies.

2023-01-27 15:19 UTC, yevgenypats approved these changes

2023-01-27 15:30 UTC, merged

2023-01-29 08:29 UTC, erezrokah commented
Trying to run this on our playground account generates quite a few errors for me:
![image](https://user-images.githubusercontent.com/26760571/215278504-c4ce8c5b-5928-447a-84e5-877fc6961d2e.png)

Looks like the defined primary keys can be `nil`. Am I missing something? Can you please verify?