fix: some properties in aws account summary remain zero or false
cloudquery/cloudquery pull request #7899
Opened 2023-02-10 15:01 UTC by KMConner

#### Summary

Some properties in the AWS Account Summary were left at their default values (e.g. 0 or false).
Properties in `Account` struct were mapped from the map returned from the AWS API. (https://docs.aws.amazon.com/sdk-for-go/api/service/iam/#IAM.GetAccountSummary)

While converting map to struct, the converter appear to be configured to refer json tag of each property.
The tags of the `Account` struct property has a json tag in the form of a snake case, but the AWS API return value is a Pascal case, so it is not correctly converted from a map to a structure.

I removed the json tags because it did not appear to be used elsewhere.

2023-02-10 17:27 UTC, candiduslynx approved these changes
Pretty neat!

https://go.dev/play/p/EOI81_gZpps
https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetAccountSummary.html

2023-02-10 23:31 UTC, bbernays commented
Great find! I think if we are removing the `json` tags we should also remove the `TagName: "json",` on this line: https://github.com/cloudquery/cloudquery/blob/f0f1e9faf3b53579daf9d4ae2509c6801e9243dd/plugins/source/aws/resources/services/iam/accounts_fetch.go#L22

2023-02-10 23:32 UTC, bbernays requested changes
Great find! I think if we are removing the `json` tags we should also remove the `TagName: "json",` on this line: https://github.com/cloudquery/cloudquery/blob/f0f1e9faf3b53579daf9d4ae2509c6801e9243dd/plugins/source/aws/resources/services/iam/accounts_fetch.go#L22

2023-02-10 23:34 UTC, bbernays commented on plugins/source/aws/resources/services/iam/accounts_mock_test.go
>  	}{}
I think this can be just replaced with `var accSummary models.Account`

2023-02-11 03:37 UTC, KMConner commented
@bbernays
I removed `TagName: "json"`.
Please review again!

2023-02-12 11:52 UTC, erezrokah approved these changes

2023-02-12 11:59 UTC, erezrokah commented
Thanks for the fix and quick follow up @KMConner I think this is ready to go 🚢

2023-02-12 12:15 UTC, merged