feat(deps): Update Elasticsearch plugin-sdk to v1.38.2
cloudquery/cloudquery pull request #8259
Opened 2023-02-20 14:22 UTC by erezrokah

#### Summary

Extracted from https://github.com/cloudquery/cloudquery/pull/8156 as it requires an additional fix.
If the table doesn't have any PKs and in overwrite mode(s) we can only write a single resource per table as the doc ID will always be the same.
This PR changes it so if there are no PKs, we use all columns for the doc ID

2023-02-20 14:47 UTC, erezrokah commented on plugins/destination/elasticsearch/client/client_test.go
> +
Once we add force migrate mode we can remove the `SkipMigrateOverwriteForce` and `SkipMigrateAppendForce`, but this is out of scope of this PR

2023-02-20 22:40 UTC, candiduslynx requested changes

2023-02-20 22:40 UTC, candiduslynx commented on plugins/destination/elasticsearch/client/write.go
> +		}
```suggestion
		for _, col := range table.Columns {
			pks = table.Columns.Names()
		}
```

2023-02-21 08:03 UTC, erezrokah commented on plugins/destination/elasticsearch/client/write.go
> +		}
Nice one 🚀

2023-02-21 08:41 UTC, candiduslynx commented on plugins/destination/elasticsearch/client/write.go
> +		}
100%

2023-02-21 08:42 UTC, candiduslynx approved these changes
I'm approving but removing automerge bc the original author (@hermanschaaf) should take a look, too.

2023-02-21 09:23 UTC, hermanschaaf approved these changes
Nice catch!

2023-02-21 12:06 UTC, merged