fix(aws!): Missing partial/parent PK for aws_ssm_instance_patches
cloudquery/cloudquery pull request #8437
Opened 2023-02-24 16:53 UTC by disq

Also clean up SSM instances code structure

2023-02-24 16:54 UTC, disq commented on plugins/source/aws/resources/services/ssm/instance_compliance_items.go
> +				Resolver: schema.ParentColumnResolver("arn"),
Change 2: Don't re-build ARN when the parent already has the same value

2023-02-24 16:54 UTC, disq commented on plugins/source/aws/resources/services/ssm/instance_patches.go
> +				Resolver: schema.ParentColumnResolver("arn"),
Change 1: Add parent `arn` here as PK, drop account_id/region PKs

2023-02-24 16:55 UTC, disq commented on plugins/source/aws/resources/services/ssm/instance_compliance_items_fetch.go
> -func resolveInstanceComplianceItemInstanceARN(_ context.Context, meta schema.ClientMeta, resource *schema.Resource, c schema.Column) error {
Part of change 2.

2023-02-27 11:34 UTC, hermanschaaf requested changes
Looks good, but since it needs to be a breaking change let's hold off on it for a bit to give us time to explore ways to make these transitions easier on users (https://github.com/cloudquery/cloudquery/issues/8474)

2023-03-30 13:41 UTC, merged