#8227 Issue: Update styles.css
cloudquery/cloudquery pull request #8440
Opened 2023-02-25 17:38 UTC by nagaajay4

#### Summary

2023-02-26 07:39 UTC, erezrokah requested changes
Hi @nagaajay4 and thank you for the PR.
Should this update the styling on light mode code snippets?
I'm seeing this on the [deploy preview](https://cloudquery-kcj20fh6g-cloudquery.vercel.app/docs/plugins/sources/aws/overview):
![image](https://user-images.githubusercontent.com/26760571/221398271-36d19dc4-d719-4d40-affc-358a6acba890.png)

2023-02-27 07:10 UTC, nagaajay4 commented
Hi @erezrokah  and thanks for pointing it out. It is working fine with new changes
![ScreenShot_27-02-2023_12_31_50](https://user-images.githubusercontent.com/51442686/221497376-3dcc045e-27f1-45be-ab19-87eed57c8e77.png)

2023-02-27 08:47 UTC, hermanschaaf commented
Hi @nagaajay4, thanks for this change, the darker background color for code snippets makes it much easier to read!

I think the style change had some unintended side-effects, though. For example, on the `/integrations/aws/bigquery` page, currently the breadcrumbs look like this:

![Screenshot 2023-02-27 at 08 42 58](https://user-images.githubusercontent.com/1121616/221515689-e3f2d726-26b6-4911-b930-9bbadfa8540f.png)

On the preview branch they look like this:

![Screenshot 2023-02-27 at 08 43 18](https://user-images.githubusercontent.com/1121616/221515711-1366d7d3-8481-4383-ad68-abbfc012ea38.png)

(The final link is a bit too light)

I also noticed that the "copy" links on the top right-hand side of code snippets are hard to see against the new background:

![Screenshot 2023-02-27 at 08 45 39](https://user-images.githubusercontent.com/1121616/221515967-6500a121-0f83-4c83-831f-68c4a1a90058.png)

Would you mind taking a look at these and seeing if there is a good solution for them?

2023-02-27 10:27 UTC, nagaajay4 commented
Hi @hermanschaaf, good observation. Thanks for letting me know. I will soon update the pr with a new solution without unintended side effects.

2023-02-27 14:54 UTC, nagaajay4 commented
Hey, @erezrokah and @hermanschaaf tried a better solution and unintended side effects are removed,(copy and toggle option links on the top right-hand side of code snippets are made clearly visible). Please let me know further suggestions or corrections.

![ScreenShot_27-02-2023_20_20_31](https://user-images.githubusercontent.com/51442686/221596678-5d6077a4-e65d-4c6f-bfd7-081376a02939.png)
![ScreenShot_27-02-2023_20_19_12](https://user-images.githubusercontent.com/51442686/221596699-9db43e4f-af9e-4ba7-8c57-8a44835aff7f.png)

2023-02-27 15:17 UTC, hermanschaaf approved these changes
Looks good to me, thanks for the fix @nagaajay4 !

2023-02-27 15:17 UTC, hermanschaaf commented on website/styles.css
> +    color: aliceblue !important;
```suggestion
  color: aliceblue !important;
```

Some extra spaces here

2023-02-27 15:18 UTC, hermanschaaf commented on website/styles.css
> +}
```suggestion
.light [data-language], .light .nextra-code-block>pre {
  background-color: #0a4b6c !important;
}
.light .nextra-code-block>div {
  background-color: #0a4b6c !important;
  color: aliceblue !important;
}
```

2023-02-27 15:32 UTC, erezrokah approved these changes
Thanks for all the follow up @nagaajay4 🚀

2023-02-27 17:57 UTC, merged