fix(aws): Parse timestamps into time values
cloudquery/cloudquery pull request #8912
Opened 2023-03-13 09:47 UTC by candiduslynx

2023-03-13 10:33 UTC, erezrokah requested changes
Great find! Let's wait for https://github.com/aws/aws-sdk-go-v2/issues/2052 so we can be positive about the new types before we introduce a breaking change

2023-03-19 16:51 UTC, erezrokah commented
Hi @candiduslynx, can we close this PR? We should probably wait until https://github.com/aws/aws-sdk/issues/492#issuecomment-1466775393 is resolved and then do this as a dependency update

2023-03-30 03:50 UTC, candiduslynx commented
@erezrokah I'm reopening this PR as https://github.com/aws/aws-sdk/issues/492 was denied proper resolution

2023-03-30 10:20 UTC, disq commented on plugins/source/aws/client/transformers.go
> +	case reflect.TypeOf(""), reflect.TypeOf(new(string)): // nop
You can do the `return schema.TypeTimestamp` here so it's easier to read

2023-03-30 10:31 UTC, erezrokah approved these changes
🚀

2023-03-30 10:37 UTC, merged