feat(aws): Add Support for DynamoDB Streams
cloudquery/cloudquery pull request #9399
Opened 2023-03-23 18:01 UTC by bbernays

#### Summary

2023-03-23 19:29 UTC, candiduslynx commented on plugins/source/aws/go.mod
> +require github.com/aws/aws-sdk-go-v2/service/dynamodbstreams v1.14.7
it's most probably a nit, but could you refactor this? (direct deps into one require, indirect into the second one + `go mod tidy`?

2023-03-27 14:37 UTC, disq requested changes

2023-03-27 14:37 UTC, disq commented on website/tables/aws/aws_dynamodbstreams_streams.md
> +This table shows data for Dynamodbstreams Streams.
This can be fixed by adding a `dynamodbstreams` entry to the `awsExceptions` map in `resources/plugin.go`

2023-03-27 15:11 UTC, disq approved these changes

2023-03-27 16:52 UTC, merged