feat(meilisearch): Meilisearch destination plugin
cloudquery/cloudquery pull request #9404
Opened 2023-03-24 11:34 UTC by candiduslynx

2023-03-28 19:07 UTC, disq reviewed
few nits

2023-03-28 19:07 UTC, disq commented on plugins/destination/meilisearch/client/client.go
> +	case specs.WriteModeOverwriteDeleteStale:
```suggestion
	default:
```

2023-03-28 19:07 UTC, disq commented on plugins/destination/meilisearch/client/client.go
> +		return nil, fmt.Errorf("%q write_mode is not supported", specs.WriteModeOverwriteDeleteStale)
```suggestion
		return nil, fmt.Errorf("%q write_mode is not supported", dstSpec.WriteMode)
```

2023-03-28 19:07 UTC, disq commented on plugins/destination/meilisearch/client/write.go
> +	var toDoc func([]any) map[string]any
Maybe define a type func for clarity?

2023-03-28 19:07 UTC, disq commented on plugins/destination/meilisearch/main.go
> +			// destination.WithDefaultBatchSize(10000),
Comments left here

2023-03-29 06:06 UTC, candiduslynx commented
We need to perform an additional `GetIndex` call in `Client.getIndexSchema` until  https://github.com/meilisearch/meilisearch-go/pull/426 is merged & released

2023-03-29 07:43 UTC, hermanschaaf commented on website/pages/docs/plugins/destinations/meilisearch/_configuration.mdx
> +    host:    "<YOUR_MEILISEARCH_HOST_PORT>"
```suggestion
    host:    "localhost:7700"
```

2023-03-29 07:46 UTC, hermanschaaf commented on website/pages/docs/plugins/destinations/meilisearch/_configuration.mdx
> +    host:    "<YOUR_MEILISEARCH_HOST_PORT>"
Or `http://localhost:7700`? Not sure, the docs lower down suggest `http://`

2023-03-29 07:56 UTC, hermanschaaf commented on website/pages/docs/plugins/destinations/meilisearch/_configuration.mdx
> +    host:    "<YOUR_MEILISEARCH_HOST_PORT>"
Yeah looks like it should be `http://localhost:7700`

2023-03-29 07:57 UTC, hermanschaaf requested changes
Nice, looks good! I haven't tested it yet, but read through the code and docs and left a few comments / questions.

2023-03-29 09:30 UTC, candiduslynx commented on plugins/destination/meilisearch/client/client.go
> +	return fmt.Errorf("DeleteStale not supported")
`DeleteStale` would require reading all index documents and then collecting their UIDs before passing them to `DeleteDocumentsBatch`.
There's a feature that's not implemented yet: https://github.com/meilisearch/product/discussions/284
After it's in the Meilisearch codebase we could implement `DeleteStale` and release a major version update.

2023-03-29 09:35 UTC, hermanschaaf approved these changes

2023-03-29 09:35 UTC, merged